package com.bfy.schedule_app.utils

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

enum class Language(val code: String, val label: String) {
    ENGLISH("en", "English"),
    VIETNAMESE("vi", "Tiếng Việt")
}

object Localization {
    var currentLanguage by mutableStateOf(Language.ENGLISH)

    private val translations = mapOf(
        Language.ENGLISH to mapOf(
            "app_settings" to "APP SETTINGS",
            "language" to "Language",
            "dark_theme" to "Dark Theme",
            "notifications" to "Notifications",
            "focus_reminders" to "Focus Reminders",
            "logout" to "LOGOUT",
            "focus_stats" to "FOCUS STATS",
            "badge_board" to "BADGE BOARD",
            "total_focus_time" to "Total Focus Time",
            "day_streak" to "Day Streak",
            "daily_avg" to "Daily Avg",
            "view_all" to "View All",
            "hello" to "Hello",
            "rank" to "Rank",
            "level" to "Level",
            "today" to "Today",
            "no_activities" to "No activities for today",
            "create_item" to "Create Item",
            "title" to "Title",
            "description" to "Description",
            "category" to "Category",
            "save" to "Save",
            "cancel" to "Cancel",
            "day" to "Day",
            "week" to "Week",
            "month" to "Month",
            "year" to "Year",
            "collaboration" to "Collaboration",
            "my_groups" to "My Groups",
            "assigned_to_me" to "Assigned to me",
            "active_groups" to "Active Groups",
            "no_groups" to "No active groups found.",
            "deep_work" to "Deep Work",
            "today_goal" to "Today's Goal",
            "start_focus" to "Start Focus",
            "pause_focus" to "Pause Focus",
            "completed" to "Completed",
            "sessions" to "sessions",
            "total_time_stat" to "Total Time",
            "mins" to "Mins",
            "group_tasks" to "Group Tasks",
            "add_category" to "Add category (+)",
            "add_todo" to "Add more (To-do)",
            "save_todo" to "Save To-do",
            "save_task" to "Save Task",
            "save_event" to "Save Event",
            "discard_title" to "Discard changes?",
            "discard_msg" to "You have unsaved data. Do you want to discard it?",
            "discard_btn" to "Discard",
            "keep_editing" to "Keep editing",
            "delete_item" to "Delete Item",
            "delete_confirm_msg" to "Are you sure you want to delete '%s'?",
            "notification" to "Notification",
            "no_notifications" to "No new notifications.",
            "home" to "Home",
            "calendar" to "Calendar",
            "focus" to "Focus",
            "profile" to "Profile",
            "minutes_label" to "MINUTES",
            "lvl" to "LVL",
            "exp" to "EXP",
            "exp_to_next" to "EXP to Next Level",
            "tasks_due_today" to "BFY: You have 3 tasks due today!",
            "january" to "January", "february" to "February", "march" to "March", "april" to "April",
            "may" to "May", "june" to "June", "july" to "July", "august" to "August",
            "september" to "September", "october" to "October", "november" to "November", "december" to "December",
            "mon" to "Mon", "tue" to "Tue", "wed" to "Wed", "thu" to "Thu", "fri" to "Fri", "sat" to "Sat", "sun" to "Sun",
            "no_desc" to "No description available",
            "active_members" to "ACTIVE MEMBERS",
            "assign_task" to "Assign Task",
            "overdue" to "Overdue",
            "in_progress" to "In Progress",
            "todo" to "To-do",
            "done" to "Done",
            "unassigned" to "Unassigned",
            "complete" to "Complete",
            "group_details" to "Group Details",
            "updated_recently" to "Updated recently",
            "items" to "Items",
            "study" to "Study",
            "work" to "Work",
            "personal" to "Personal",
            "focus_start_title" to "Start Focus Mode",
            "focus_start_msg" to "Do you want to start focus mode now? Once started, you should stay on this screen to maintain focus.",
            "focus_stop_title" to "Stop Focus Session?",
            "focus_stop_msg" to "If you stop now, your progress will be reset. Are you sure you want to exit focus mode?",
            "focus_stop_btn" to "Stop & Reset",
            "focus_stay_btn" to "Continue Focusing",
            "exit_focus_title" to "Exit Focus Mode?",
            "exit_focus_msg" to "Leaving this screen will stop and reset your focus timer. Do you want to continue?",
            "exit_reset_btn" to "Exit & Reset",
            "stay_btn" to "Stay",
            "ok" to "OK",
            "loading" to "Loading...",
            "unknown_user" to "Unknown User",
            "sign_in" to "Sign In",
            "sign_up" to "Sign Up",
            "email_address" to "Email Address",
            "password" to "Password",
            "full_name" to "Full Name",
            "signing_in" to "Signing In...",
            "signing_up" to "Signing Up...",
            "dont_have_account" to "Don't have an account? ",
            "already_have_account" to "Already have an account? ",
            "or" to "OR",
            "delete" to "Delete",
            "processing" to "Processing...",
            "update" to "Update",
            "repeat" to "Repeat",
            "set_reminder" to "Set Reminder",
            "all_day" to "All day",
            "start_time" to "Start time",
            "end_time" to "End time",
            "reminder_options_label" to "Reminder options",
            "alarm_reminders" to "Alarm reminders",
            "countdown_reminder" to "Countdown reminder",
            "add_category_title" to "Add category",
            "category_name" to "Category name",
            "add" to "Add",
            "task" to "Task",
            "event" to "Event",
            "never" to "Never",
            "daily" to "Daily",
            "mon_fri" to "Mon-Fri",
            "weekly" to "Weekly",
            "monthly" to "Monthly",
            "yearly" to "Yearly",
            "starts" to "Starts",
            "min_5" to "5m",
            "min_10" to "10m",
            "min_30" to "30m",
            "hour_1" to "1h",
            "day_1" to "1 day",
            "week_1" to "1 week",
            "custom" to "Custom",
            "title_required" to "Title is required.",
            "title_too_long" to "Title must be at most 100 characters.",
            "what_needs_done" to "What needs to be done?",
            "add_details" to "Add details...",
            "toggle_time_rem" to "Toggle to set time and reminder",
            "full_day_task_event" to "Turn on for full-day task/event",
            "play_sound_rem" to "Play sound when reminder triggers",
            "enable_foreground_countdown" to "Enable foreground countdown notification",
            "today_schedule" to "Today's Schedule",
            "no_schedule_today" to "No schedules for today",
            "search" to "Search",
            "mark_done" to "Mark as Done",
            "edit" to "Edit",
            "bio" to "Bio",
            "edit_profile" to "Edit Profile",
            "email" to "Email",
            "set_time" to "Set Time"
        ),
        Language.VIETNAMESE to mapOf(
            "app_settings" to "CÀI ĐẶT ỨNG DỤNG",
            "language" to "Ngôn ngữ",
            "dark_theme" to "Chế độ tối",
            "notifications" to "Thông báo",
            "focus_reminders" to "Nhắc nhở tập trung",
            "logout" to "ĐĂNG XUẤT",
            "focus_stats" to "THỐNG KÊ TẬP TRUNG",
            "badge_board" to "BẢNG DANH HIỆU",
            "total_focus_time" to "Tổng thời gian tập trung",
            "day_streak" to "Chuỗi ngày",
            "daily_avg" to "T.bình hàng ngày",
            "view_all" to "Xem tất cả",
            "hello" to "Xin chào",
            "rank" to "Hạng",
            "level" to "Cấp độ",
            "today" to "Hôm nay",
            "no_activities" to "Không có hoạt động nào hôm nay",
            "create_item" to "Tạo mới",
            "title" to "Tiêu đề",
            "description" to "Mô tả",
            "category" to "Danh mục",
            "save" to "Lưu",
            "cancel" to "Hủy",
            "day" to "Ngày",
            "week" to "Tuần",
            "month" to "Tháng",
            "year" to "Năm",
            "collaboration" to "Cộng tác",
            "my_groups" to "Nhóm của tôi",
            "assigned_to_me" to "Giao cho tôi",
            "active_groups" to "Nhóm đang hoạt động",
            "no_groups" to "Không tìm thấy nhóm nào.",
            "deep_work" to "Làm việc sâu",
            "today_goal" to "Mục tiêu hôm nay",
            "start_focus" to "Bắt đầu tập trung",
            "pause_focus" to "Tạm dừng",
            "completed" to "Đã hoàn thành",
            "sessions" to "phiên",
            "total_time_stat" to "Tổng thời gian",
            "mins" to "Phút",
            "group_tasks" to "Công việc nhóm",
            "add_category" to "Thêm danh mục (+)",
            "add_todo" to "Thêm việc cần làm",
            "save_todo" to "Lưu việc cần làm",
            "save_task" to "Lưu nhiệm vụ",
            "save_event" to "Lưu sự kiện",
            "discard_title" to "Hủy thay đổi?",
            "discard_msg" to "Bạn có dữ liệu chưa lưu. Bạn có muốn hủy không?",
            "discard_btn" to "Hủy bỏ",
            "keep_editing" to "Tiếp tục sửa",
            "delete_item" to "Xóa mục",
            "delete_confirm_msg" to "Bạn có chắc chắn muốn xóa '%s' không?",
            "notification" to "Thông báo",
            "no_notifications" to "Không có thông báo mới.",
            "home" to "Trang chủ",
            "calendar" to "Lịch",
            "focus" to "Tập trung",
            "profile" to "Cá nhân",
            "minutes_label" to "PHÚT",
            "lvl" to "Cấp",
            "exp" to "EXP",
            "exp_to_next" to "EXP để lên cấp",
            "tasks_due_today" to "BFY: Bạn có 3 nhiệm vụ cần hoàn thành hôm nay!",
            "january" to "Tháng 1", "february" to "Tháng 2", "march" to "Tháng 3", "april" to "Tháng 4",
            "may" to "Tháng 5", "june" to "Tháng 6", "july" to "Tháng 7", "august" to "Tháng 8",
            "september" to "Tháng 9", "october" to "Tháng 10", "november" to "Tháng 11", "december" to "Tháng 12",
            "mon" to "Thứ 2", "tue" to "Thứ 3", "wed" to "Thứ 4", "thu" to "Thứ 5", "fri" to "Thứ 6", "sat" to "Thứ 7", "sun" to "Chủ nhật",
            "no_desc" to "Không có mô tả",
            "active_members" to "THÀNH VIÊN HOẠT ĐỘNG",
            "assign_task" to "Giao việc",
            "overdue" to "Quá hạn",
            "in_progress" to "Đang làm",
            "todo" to "Cần làm",
            "done" to "Hoàn thành",
            "unassigned" to "Chưa giao",
            "complete" to "Hoàn thành",
            "group_details" to "Chi tiết nhóm",
            "updated_recently" to "Vừa cập nhật",
            "items" to "Mục",
            "study" to "Học tập",
            "work" to "Công việc",
            "personal" to "Cá nhân",
            "focus_start_title" to "Bắt đầu chế độ tập trung",
            "focus_start_msg" to "Bạn có muốn bắt đầu chế độ tập trung ngay bây giờ không? Sau khi bắt đầu, bạn nên ở lại màn hình này để duy trì sự tập trung.",
            "focus_stop_title" to "Dừng phiên tập trung?",
            "focus_stop_msg" to "Nếu bạn dừng bây giờ, tiến trình của bạn sẽ bị xóa sạch. Bạn có chắc chắn muốn thoát chế độ tập trung không?",
            "focus_stop_btn" to "Dừng & Đặt lại",
            "focus_stay_btn" to "Tiếp tục tập trung",
            "exit_focus_title" to "Thoát chế độ tập trung?",
            "exit_focus_msg" to "Rời khỏi màn hình này sẽ dừng và đặt lại bộ hẹn giờ tập trung của bạn. Bạn có muốn tiếp tục không?",
            "exit_reset_btn" to "Thoát & Đặt lại",
            "stay_btn" to "Ở lại",
            "ok" to "Đồng ý",
            "loading" to "Đang tải...",
            "unknown_user" to "Người dùng ẩn danh",
            "sign_in" to "Đăng nhập",
            "sign_up" to "Đăng ký",
            "email_address" to "Địa chỉ Email",
            "password" to "Mật khẩu",
            "full_name" to "Họ và tên",
            "signing_in" to "Đang đăng nhập...",
            "signing_up" to "Đang đăng ký...",
            "dont_have_account" to "Chưa có tài khoản? ",
            "already_have_account" to "Đã có tài khoản? ",
            "or" to "HOẶC",
            "delete" to "Xóa",
            "processing" to "Đang xử lý...",
            "update" to "Cập nhật",
            "repeat" to "Lặp lại",
            "set_reminder" to "Đặt nhắc nhở",
            "all_day" to "Cả ngày",
            "start_time" to "Giờ bắt đầu",
            "end_time" to "Giờ kết thúc",
            "reminder_options_label" to "Tùy chọn nhắc nhở",
            "alarm_reminders" to "Chuông nhắc nhở",
            "countdown_reminder" to "Đếm ngược",
            "add_category_title" to "Thêm danh mục",
            "category_name" to "Tên danh mục",
            "add" to "Thêm",
            "task" to "Nhiệm vụ",
            "event" to "Sự kiện",
            "never" to "Không bao giờ",
            "daily" to "Hàng ngày",
            "mon_fri" to "T2-T6",
            "weekly" to "Hàng tuần",
            "monthly" to "Hàng tháng",
            "yearly" to "Hàng năm",
            "starts" to "Bắt đầu",
            "min_5" to "5 phút",
            "min_10" to "10 phút",
            "min_30" to "30 phút",
            "hour_1" to "1 giờ",
            "day_1" to "1 ngày",
            "week_1" to "1 tuần",
            "custom" to "Tùy chỉnh",
            "title_required" to "Tiêu đề là bắt buộc.",
            "title_too_long" to "Tiêu đề tối đa 100 ký tự.",
            "what_needs_done" to "Cần làm gì?",
            "add_details" to "Thêm chi tiết...",
            "toggle_time_rem" to "Bật để đặt thời gian và nhắc nhở",
            "full_day_task_event" to "Bật cho nhiệm vụ/sự kiện cả ngày",
            "play_sound_rem" to "Phát âm thanh khi đến giờ",
            "enable_foreground_countdown" to "Bật thông báo đếm ngược",
            "today_schedule" to "Lịch trình hôm nay",
            "no_schedule_today" to "Hôm nay chưa có lịch trình",
            "search" to "Tìm kiếm",
            "mark_done" to "Đánh dấu xong",
            "edit" to "Sửa",
            "bio" to "Tiểu sử",
            "edit_profile" to "Chỉnh sửa hồ sơ",
            "email" to "Email",
            "set_time" to "Chọn giờ"
        )
    )

    fun get(key: String): String {
        return translations[Language.ENGLISH]?.get(key.lowercase()) ?: key
    }

    fun getMonth(month: kotlinx.datetime.Month): String {
        return get(month.name.lowercase())
    }

    fun getDayOfWeek(day: kotlinx.datetime.DayOfWeek): String {
        return get(day.name.lowercase().take(3))
    }
}
